### ISSUE TITLE
I'm in trouble in creating a Npm and Redex package

### ISSUE THREAD

**Issue by Acciaiodigitale** [aaronshaf/reasonml-fastify#4]
@aaronshaf Can we chat a moment so I can go ahead? Actually the example work only if it is in the same src as the Fastify module.....

I don't have clue why

**Comment by Acciaiodigitale** [comment]
Yes. I downloaded the module and after yarn predeploy I give yarn link.
Then I create a new bsb project and copied the example there and make yarn link 'fastify-with-reason' and added to bs-config but on the yarn build don't find Fastify

**Comment by Acciaiodigitale** [comment]
I found my way to use reasonml-fastify as a module:

```
open ReasonFastify.Fastify;

let app = createServer(~logger=true);
app->get("/", Index.handler);
app->listen(3000, result =>
  switch (result) {
  | Ok(_address) => ()
  | Error(error) =>
    app->logError(error);
    Node.Process.exit(1);
  }
);
```

I think this is due to the name of the package so that reasonml-fastify  become **ReasonFastify** and src/Fastify.re become the **Fastify** in:

`open ReasonFastify.Fastify;`

**Comment by aaronshaf** [comment]
https://bucklescript.github.io/docs/en/build-configuration.html

> You can activate namespacing through "namespace": true in your bsconfig.json

I think setting `namespace` to false in bsconfig might turn `ReasonFastify.Fastify` into merely `Fastify`?

**Comment by Acciaiodigitale** [comment]
Yes, it is....sorry but I don't always find the right docs between Reason, Bucklescript and other site....!!

**Comment by aaronshaf** [comment]
Thanks for what you're doing!
